project:
  type: website
  output-dir: docs

website:
  title: "Alex Matrajt Frid"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: skills.qmd
        text: Skills
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: blogs.qmd
        text: Blogs

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
